// Explicit registry of every lucide-react icon referenced by name in
// services-data.ts (SubService.icon values). Components that look up an
// icon by string key must go through this map rather than
// `import * as Icons from "lucide-react"` — a wildcard import defeats
// tree-shaking because the bundler can't tell which icons a dynamic
// `Icons[key]` lookup will use, so it ships the entire ~1000-icon library.
import {
    ArrowLeftRight,
    BadgeCheck,
    BookOpenCheck,
    BrainCircuit,
    Calculator,
    ClipboardCheck,
    Coins,
    Cpu,
    Fingerprint,
    Flame,
    FileCheck2,
    FileSignature,
    FileText,
    FolderTree,
    Gauge,
    Gavel,
    Gem,
    Globe2,
    GraduationCap,
    Hammer,
    Landmark,
    Leaf,
    LineChart,
    ListTree,
    Lock,
    MapPinned,
    PackageSearch,
    Receipt,
    Rocket,
    Scale,
    Search,
    ShieldAlert,
    ShieldCheck,
    ShoppingCart,
    Sparkle,
    Stethoscope,
    Store,
    TrendingUp,
    Users,
    Vault,
    type LucideIcon,
} from "lucide-react";

export const serviceIcons: Record<string, LucideIcon> = {
    ArrowLeftRight,
    BadgeCheck,
    BookOpenCheck,
    BrainCircuit,
    Calculator,
    ClipboardCheck,
    Coins,
    Cpu,
    Fingerprint,
    Flame,
    FileCheck2,
    FileSignature,
    FileText,
    FolderTree,
    Gauge,
    Gavel,
    Gem,
    Globe2,
    GraduationCap,
    Hammer,
    Landmark,
    Leaf,
    LineChart,
    ListTree,
    Lock,
    MapPinned,
    PackageSearch,
    Receipt,
    Rocket,
    Scale,
    Search,
    ShieldAlert,
    ShieldCheck,
    ShoppingCart,
    Stethoscope,
    Store,
    TrendingUp,
    Users,
    Vault,
};

export function getServiceIcon(name: string | undefined): LucideIcon {
    return (name && serviceIcons[name]) || Sparkle;
}
